@startuml
set namespaceSeparator ?
hide circle
hide class fields

package IG #DDDDDD{

     package Profiles #DDDDDD{

        class ActorChild{

             ActorChild => [None..None]
             ActorChild.XCN1[x] => [None..None]
        } 

        class ActorChild2{

             ActorChild2 => [None..None]
             ActorChild2.XCN1[x] => [None..None]
             ActorChild2.XCN3 => [None..None]
        } 

        class ActorParent{

             ActorParent => [None..None]
             ActorParent.XCN1[x] => [1..1]
             ActorParent.XCN3 => [1..1]
        } 

        class Choice1{

        } 

        class Choice2{

        } 

        class Choice3{

         }

     }
     package extension #paleturquoise {


         }
     }
     package valueset #PaleVioletRed{
       }

package "Ressources de base" #palegreen {

 class "https://interop.esante.gouv.fr/ig/fhir/pdsm4dmp/StructureDefinition/ActorParent" as  class5b81927f666ca2324a3cdc0f71a4ef0c 

    class5b81927f666ca2324a3cdc0f71a4ef0c --> ActorChild

 class "https://interop.esante.gouv.fr/ig/fhir/pdsm4dmp/StructureDefinition/ActorParent" as  class5b81927f666ca2324a3cdc0f71a4ef0c 

    class5b81927f666ca2324a3cdc0f71a4ef0c --> ActorChild2

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> ActorParent

 class "string" as  classb45cffe084dd3d20d928bee85e7b0f21 

    classb45cffe084dd3d20d928bee85e7b0f21 --> Choice1

 class "string" as  classb45cffe084dd3d20d928bee85e7b0f21 

    classb45cffe084dd3d20d928bee85e7b0f21 --> Choice2

 class "string" as  classb45cffe084dd3d20d928bee85e7b0f21 

    classb45cffe084dd3d20d928bee85e7b0f21 --> Choice3
}
@enduml