@startuml
set namespaceSeparator ?
hide circle
hide class fields

package IG #DDDDDD{

     package Profiles #DDDDDD{

        class Author{

             Author => [None..None]
             Author.institution => [0..1]
             Author.person => [1..1]
             Author.role => [1..1]
             Author.specialty => [0..1]
        } 

        class AuthorInstitution{

             AuthorInstitution => [None..None]
             AuthorInstitution.1 => [1..1]
             AuthorInstitution.6 => [1..1]
             AuthorInstitution.7 => [1..1]
             AuthorInstitution.10 => [1..1]
        } 

        class AuthorPerson{

             AuthorPerson => [None..None]
             AuthorPerson.1 => [1..1]
             AuthorPerson.2 => [1..1]
             AuthorPerson.3 => [1..1]
             AuthorPerson.9 => [1..1]
             AuthorPerson.10 => [1..1]
             AuthorPerson.13 => [1..1]
        } 

        class DocumentEntry{

             DocumentEntry => [None..None]
             DocumentEntry.entryUUID => [1..1]
             DocumentEntry.logicalId => [1..1]
             DocumentEntry.mimeType => [1..1]
             DocumentEntry.availabilityStatus => [1..1]
             DocumentEntry.hash => [1..1]
             DocumentEntry.size => [1..1]
             DocumentEntry.languageCode => [1..1]
             DocumentEntry.author => [1..*]
             DocumentEntry.legalAuthenticator => [1..1]
             DocumentEntry.repositoryUniqueId => [1..1]
             DocumentEntry.serviceStartTime => [1..1]
             DocumentEntry.serviceEndTime => [0..1]
             DocumentEntry.sourcePatientID => [1..1]
             DocumentEntry.sourcePatientInfo => [1..1]
             DocumentEntry.URI => [1..1]
             DocumentEntry.title => [1..1]
             DocumentEntry.comments => [0..1]
             DocumentEntry.patientID => [1..1]
             DocumentEntry.uniqueId => [1..1]
             DocumentEntry.class => [1..1]
             DocumentEntry.confidentiality => [1..4]
             DocumentEntry.eventCodeList => [0..*]
             DocumentEntry.format => [1..1]
             DocumentEntry.healthcareFacilityTypeCode => [1..1]
             DocumentEntry.practiceSetting => [1..1]
             DocumentEntry.type => [1..1]
             DocumentEntry.documentAvailability => [0..1]
             DocumentEntry.homeCommunityId => [0..1]
             DocumentEntry.creationTime => [1..1]
             DocumentEntry.referenceIdList => [0..*]
             DocumentEntry.referenceIdList.CX1 => [1..1]
             DocumentEntry.referenceIdList.CX4 => [1..1]
             DocumentEntry.referenceIdList.CX5 => [1..1]
             DocumentEntry.version => [0..1]
        } 

        class EventCode{

             EventCode => [None..None]
             EventCode.eventCode => [1..1]
        } 

        class LegalAuthenticator{

             LegalAuthenticator => [None..None]
             LegalAuthenticator.1 => [1..1]
             LegalAuthenticator.2 => [1..1]
             LegalAuthenticator.3 => [1..1]
             LegalAuthenticator.9 => [1..1]
             LegalAuthenticator.10 => [1..1]
             LegalAuthenticator.13 => [1..1]
        } 

        class PSIdNat{

        } 

        class PatientId{

             PatientId => [None..None]
             PatientId.1 => [1..1]
             PatientId.4 => [1..1]
             PatientId.5 => [1..1]
        } 

        class SourcePatientId{

             SourcePatientId => [None..None]
             SourcePatientId.1 => [1..1]
             SourcePatientId.4 => [1..1]
             SourcePatientId.5 => [1..1]
        } 

        class SourcePatientInfo{

             SourcePatientInfo => [None..None]
             SourcePatientInfo.PID => [1..1]
             SourcePatientInfo.PID.3 => [0..1]
             SourcePatientInfo.PID.5 => [1..*]
             SourcePatientInfo.PID.7 => [0..1]
             SourcePatientInfo.PID.8 => [0..1]
             SourcePatientInfo.PID.11 => [0..1]
             SourcePatientInfo.PID.13 => [0..1]
             SourcePatientInfo.PID.14 => [0..1]
             SourcePatientInfo.PID.15 => [0..1]
             SourcePatientInfo.PID.16 => [0..1]
             SourcePatientInfo.PID.18 => [0..1]
             SourcePatientInfo.PID.21 => [0..1]
        } 

        class StructIdNat{

        } 

        class SubmissionSet{

             SubmissionSet => [None..None]
             SubmissionSet.entryUUID => [1..1]
             SubmissionSet.availabilityStatus => [1..1]
             SubmissionSet.submissionTime => [1..1]
             SubmissionSet.title => [0..1]
             SubmissionSet.comments => [0..1]
             SubmissionSet.patientID => [1..1]
             SubmissionSet.sourceID => [1..1]
             SubmissionSet.uniqueID => [1..1]
             SubmissionSet.contentTypeCode => [1..1]
             SubmissionSet.author => [1..1]
             SubmissionSet.homeCommunityID => [0..1]
             SubmissionSet.intendedRecipient => [0..*]
         }

     }
     package extension #paleturquoise {


         }
     }
     package valueset #PaleVioletRed{
       }

package "Ressources de base" #palegreen {

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> Author

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> AuthorInstitution

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> AuthorPerson

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> DocumentEntry

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> EventCode

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> LegalAuthenticator

 class "integer" as  class157db7df530023575515d366c9b672e8 

    class157db7df530023575515d366c9b672e8 --> PSIdNat

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> PatientId

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> SourcePatientId

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> SourcePatientInfo

 class "integer" as  class157db7df530023575515d366c9b672e8 

    class157db7df530023575515d366c9b672e8 --> StructIdNat

 class "Base" as  class095a1b43effec73955e31e790438de49 

    class095a1b43effec73955e31e790438de49 --> SubmissionSet
}
@enduml